export type Campaign = {
  campaign_name: string;
  campaign_id: string;
  campaign_status: number;
  campaign_is_evergreen: boolean;
  leads_count: number;
  contacted_count: number;
  open_count: number;
  reply_count: number;
  link_click_count: number;
  bounced_count: number;
  unsubscribed_count: number;
  completed_count: number;
  emails_sent_count: number;
  new_leads_contacted_count: number;
  total_opportunities: number;
  total_opportunity_value: number;
};

export type Lead = {
  row_number: number;
  "Property Owner Name": string;
  Line1: string;
  Line2: string;
  Attom_ID: number;
  Apify: string;
  Email1: string;
  Email2: string;
  Email3: string;
  Email4: string;
  Email5: string;
  Age: number | string;
  Born: string;
  "Previous Addresses": string;
  Phone: string;
  Relatives: string;
  "Current Address": string;
  "All Emails": string;
  Valid_Emails: string;
  Rooms: string;
  Size: string;
  "Property Type": string;
  Gmail: string;
  Valid_email: string;
  "AI Message": string;
};
